- name: Install Docker
  shell: curl -sSL https://get.docker.io | bash

- name: Check the Docker Version  
  shell: docker --version 

- name: Create the drop-in unit directory for docker.service
  file: state=directory path=/etc/systemd/system/docker.service.d

- name: Create docker user
  user:
    name: root
    group: root
    groups: root,docker
    append: yes 

- name: Install Epel-release
  yum: name=epel-release state=latest

- name: Install dependencies for Ansible
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - python-devel
    - python-pip
    - libffi-devel
    - openssl-devel
    - bridge-utils

- name: Run these commands to reload the daemon
  shell: systemctl daemon-reload;systemctl restart docker

- name: Install Docker-Py
  pip:
    name: docker-py

- name: Install Docker-compose 
  pip: 
    name: docker-compose

- name: Install Docker-Machine
  shell: "curl -L https://github.com/docker/machine/releases/download/v0.9.0-rc2/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && chmod +x /usr/local/bin/docker-machine"
   
- name: Container Test / application service
  docker:
    name: helloworld
    image: rickfast/hello-oreilly
    state: restarted

- name: Start the Rancher Docker container
  docker: |
    image="rancher/server:{{ rancher_server_tag }}"
    ports="8080:{{ rancher_server_port }}"
    docker_api_version="{{ docker_api_version.stdout }}"

- name: Wait for the daemon to start up
  wait_for: port=8080
