#----
- name: Install Epel-release 
  yum: name=epel-release state=latest

- name: Install dependencies for Ansible
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - python-devel
    - python-pip
    - libffi-devel
    - openssl-devel

- name: Install Python Cryptography
  pip: name=cryptography
